apiVersion: v1
kind: Pod
metadata:
  name: haproxy-pod
spec:
  containers:
  - name: haproxy
    image: bardiayaghmaie/pr04-haproxy:1.2
    ports:
    - containerPort: 80
    - containerPort: 8404
  # Add other configuration like volumes, environment variables, etc. if needed
